redis:
  extends:
    file: docker-compose-common.yml
    service: redis

restaurants:
  extends:
    file: docker-compose-common.yml
    service: restaurants
  volumes:
    - ./restaurants-service/build/libs:/app
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

restaurantsview:
  extends:
    file: docker-compose-common.yml
    service: restaurantsview
  volumes:
    - ./restaurants-view-service/build/libs:/app
  links:
    - redis
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}